image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - cd examples/csv_examples/csv_basic_example/
  - rm -rf .terraform
  - terraform --version
  - mkdir -p ../../../creds
  - echo $SERVICEACCOUNT > ../../../creds/serviceaccount.json
  - cat ../../../creds/serviceaccount.json
  - terraform init -upgrade
  - echo "Running pipeline with additional Terraform options - $TERRAFORM_OPTIONS"

stages:
  - validate
  - plan
  - apply
  - commit
  - push
  - revert

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -var="pan_creds=../../../creds/serviceaccount.json" -var="panorama_mode=true" $TERRAFORM_OPTIONS
  dependencies:
    - validate

apply:
  stage: apply
  script:
    - terraform apply -auto-approve -var="pan_creds=../../../creds/serviceaccount.json" -var="panorama_mode=true" $TERRAFORM_OPTIONS
  dependencies:
    - plan
  only:
    - main
    - demo

commit:
  stage: commit
  script:
    - apk update && apk add go
    - cd ../../../utils
    - go mod init panorama_commit_push
    - go mod tidy
    - go build panorama_commit_push.go
    # - ./panorama_commit_push -config ../creds/serviceaccount.json -deviceGroup "AWSGlobalProtectFirewalls"
    - ./panorama_commit_push -config ../creds/serviceaccount.json -deviceGroup "$DEVICE_GROUP"
  dependencies:
    - apply
  only:
    - main
    - demo

push:
  stage: push
  script:
    - apk update && apk add go
    - cd ../../../utils
    - go mod init panorama_commit_push
    - go mod tidy
    - go build panorama_commit_push.go
    # - ./panorama_commit_push -config ../creds/serviceaccount.json -mode "push" -deviceGroup "AWSGlobalProtectFirewalls" -devices "007255000331988" -templateStack "default-stack"
    - ./panorama_commit_push -config ../creds/serviceaccount.json -mode "push" -deviceGroup "$DEVICE_GROUP" -devices "$DEVICES" -templateStack "$TEMPLATE_STACK"
  dependencies:
    - apply
  only:
    - main
    - demo

revert:
  stage: revert
  script:
    - git reset --hard HEAD^
    - terraform apply -auto-approve -var="pan_creds=../../../creds/serviceaccount.json" -var="panorama_mode=true" $TERRAFORM_OPTIONS
    - apk update && apk add go
    - cd ../../../utils
    - go mod init panorama_commit_push
    - go mod tidy
    - go build panorama_commit_push.go
    - ./panorama_commit_push -config ../creds/serviceaccount.json -deviceGroup "$DEVICE_GROUP"
    - ./panorama_commit_push -config ../creds/serviceaccount.json -mode "push" -deviceGroup "$DEVICE_GROUP" -devices "$DEVICES" -templateStack "$TEMPLATE_STACK"
  dependencies:
    - push
  only:
    - main
    - demo
  when: on_failure
