# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - cd examples/csv_examples/csv_basic_example/
  - rm -rf .terraform
  - terraform --version
  - mkdir -p ./creds
  - apk update && apk add go
  - echo $SERVICEACCOUNT > ./creds/serviceaccount.json
  - cat ./creds/serviceaccount.json
  - terraform init -upgrade
  - echo "Running pipeline with additional Terraform options - $TERRAFORM_OPTIONS"

stages:
  - validate
  - plan
  - apply
  - commit 

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -var="pan_creds=./creds/serviceaccount.json" -var="panorama_mode=true" $TERRAFORM_OPTIONS
  dependencies:
    - validate

apply:
  stage: apply
  script:
    - terraform apply -auto-approve -var="pan_creds=./creds/serviceaccount.json" -var="panorama_mode=true" $TERRAFORM_OPTIONS
  dependencies:
    - plan
  only:
    - main
    - demo

commit:
  stage: commit
  script:
    # - go get github.com/PaloAltoNetworks/pango
    # - go build firewall-commit.go
    # - ./firewall-commit -config ./creds/serviceaccount.json 'Changes committed automatically by pipeline'
    - cd commit
    - go mod init fw_commit
    - go mod tidy
    - go build fw_commit.go
    - ./fw_commit -config ./creds/serviceaccount.json
  dependencies:
    - apply
  only:
    - main
    - demo
