image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - cd examples/csv_examples/csv_basic_example/
  - rm -rf .terraform
  - terraform --version
  - mkdir -p ../../../creds
  - apk update && apk add go
  - echo $SERVICEACCOUNT > ../../../creds/serviceaccount.json
  - cat ../../../creds/serviceaccount.json
  - terraform init -upgrade
  - echo "Running pipeline with additional Terraform options - $TERRAFORM_OPTIONS"

stages:
  - validate
  - plan
  - apply
  - commit
  - push

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -var="pan_creds=../../../creds/serviceaccount.json" -var="panorama_mode=true" $TERRAFORM_OPTIONS
  dependencies:
    - validate

apply:
  stage: apply
  script:
    - terraform apply -auto-approve -var="pan_creds=../../../creds/serviceaccount.json" -var="panorama_mode=true" $TERRAFORM_OPTIONS
  dependencies:
    - plan
  only:
    - main
    - demo

commit:
  stage: commit
  script:
    - cd ../../../utils
    - go mod init commit
    - go mod tidy
    - go build commit_pano.go
    - ./commit_pano -config ../creds/serviceaccount.json
  dependencies:
    - apply
  only:
    - main
    - demo

push:
  stage: push
  script:
    - cd ../../../utils
    - go mod tidy
    - go build push_pano.go
    - ./push_pano -config ../creds/serviceaccount.json
  dependencies:
    - apply
  only:
    - main
    - demo