name: Release CI
run-name: "Continuous Release"

permissions:
  contents: write
  issues: read
  id-token: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 4' # this means every Thursday @1am UTC

concurrency: release

jobs:
  release_wrkflw:
    name: Do release
    uses: PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/.github/workflows/release_ci.yml@v2.3
    if: github.actor != 'dependabot[bot]'
    secrets: inherit
    with:
      cloud: aws
      validate_max_parallel: 20
      test_max_parallel: 5
      terratest_action: Plan # keep in mind that this has to start with capital letter
      fail_fast: false
      apply_timeout: 120
